### ISSUE TITLE
Question rather than issue

### ISSUE THREAD

**Issue by MihneaSe** [Madelena/Metrology-for-Beeper#1]
Hello,
As I was not sure how to get in touch with you I prefer to write here directly.
Great theme, and also thanks for keeping it updated with all the changes that the Beeper team is doing :).

I wanted to ask you 2 questions:
1. How to remove the gradient from the messages I sent in the main box?
2. When changing the Hue, the color from the left panel does not match the color from the main window, is that normal?
3. Not sure if this is for you or for Beeper, but asking anyway :) is it possible to remove the favorites images and put just the names instead?
Thanks!

**Comment by Madelena** [comment]
Hello! 😺 Thanks for your appreciation!!

1. The easiest way to do it is to change the fourth line `--metrology-complement: calc(var(--metrology-hue) - 50), 100%, 28%;` to `--metrology-complement: var(--metrology-hue), 100%, 38%;`
2. Hmm. I don't think I'm able to reproduce the bug. Can you post a screenshot?
3. That would be a question for the Beeper team.

**Comment by MihneaSe** [comment]
thanks

**Comment by MihneaSe** [comment]
oh and for my 2nd question, I think I messed up with some of the code from your initial version that is why :-)
