### ISSUE TITLE
Please update for the recent refactor to the Beeper UI

### ISSUE THREAD

**Issue by MulverineX** [Madelena/Metrology-for-Beeper#11]
![image](https://github.com/Madelena/Metrology-for-Beeper/assets/12068027/506717f5-de8d-4628-a077-adcfd2c9253d)

**Comment by MulverineX** [comment]
![image](https://github.com/Madelena/Metrology-for-Beeper/assets/12068027/09ad7440-6cdc-43b7-a81f-e98a821f9765)

**Comment by MulverineX** [comment]
![image-EDIT](https://github.com/Madelena/Metrology-for-Beeper/assets/12068027/ed5e0186-bb36-45f8-a7f2-1002f52fc483)

**Comment by Madelena** [comment]
Should be fixed now :)

**Comment by MulverineX** [comment]
Thank you!!
