### ISSUE TITLE
Another question :)

### ISSUE THREAD

**Issue by MihneaSe** [Madelena/Metrology-for-Beeper#2]
Me again :)

I would like to add a bit of space between the text from the preview on the left panel and the border between the left panel and the main screen, I assume is here, but does not seem to work with "border-right", what I am doing wrong?

.bp_LeftPanel .rooms_subtitle {
  font-size: 16px;
  line-height: 16px;
  margin-bottom: 4px;
  color: hsl(var(--metrology-text-secondary)) !important;
  opacity: 1 !important;
  padding-left: 32px !important;
 }

**Comment by Madelena** [comment]
Is this still a bug? I noticed that you said this is resolved on your end on #1

**Comment by MihneaSe** [comment]
![Capture d’écran 2023-02-01 213150](https://user-images.githubusercontent.com/45152388/216156810-e89afb65-a35a-4424-bd51-95c7dbd04d7e.png)

what I meant to say with my first question is that the preview text color is not the same as the background of the messaging part, and depending on the color I choose it looks strange, but not a bug per se. Sorry for not being clear.

**Comment by Madelena** [comment]
The bubbles have a slight gradient to it for flair, so the colors are not flat.
