### ISSUE TITLE
Voice messages color issue

### ISSUE THREAD

**Issue by philipp-winterle** [Madelena/Metrology-for-Beeper#5]
If you send a voice message in dark mode the display for the acknowledge line is blue. See screen.

This only happens for own messages.

Beeper Mac
beeper-desktop version: 3.60.21

<img width="327" alt="CleanShot 2023-06-22 at 10 23 33@2x" src="https://github.com/Madelena/Metrology-for-Beeper/assets/633711/3b5a655b-b9cf-4f47-be23-19f65807c94e">

**Comment by G0razd** [comment]
Hey,
it's not only voice messages, it's message reactions also.
When adding reaction there is a blue bar under the message
![image](https://github.com/Madelena/Metrology-for-Beeper/assets/74553402/b9bfbd53-30ba-4557-9956-d1afe5960884)

Beeper Windows
beeper-desktop version: 3.66.23

**Comment by llsaboya** [comment]
Image captions also have this issue. I fixed with this line.

`
.mx_EventTile_messageOut .mx_EventTile_caption,
.mx_EventTile_messageOut .mx_EventTile_content-caption {
  background: transparent !important;
}
`
