### ISSUE TITLE
Question: Is there any way to make it more OLED-friendly?

### ISSUE THREAD

**Issue by atmanli** [Madelena/Metrology-for-Beeper#9]
I love the theme, excellent work!

I do have a question, though. Is there a way to make this theme more OLED-friendly? Specifically, I'd like to give the left part, where the chat preview and messenger icons are, a black background. Is that possible?

**Comment by Madelena** [comment]
Thank you! And, yes! You can find this at the top of the code:

```
  /* Dark Theme */
  --metrology-background: 0, 0%, 0%;
  --metrology-text-primary: 0, 0%, 100%;
  --metrology-text-heading: 0, 0%, 95%;
  --metrology-text-secondary: 0, 0%, 66%;

  --metrology-gray-1: 0, 0%, 9%;
  --metrology-gray-2: 0, 0%, 15%;
  --metrology-gray-3: 0, 0%, 21%;
  --metrology-gray-6: 0, 0%, 46%;
  --metrology-shadow: 0, 0%, 0%, 0.25;

  --message-color-lightness: 100%;
  --message-bg-saturation: 25%;
  --message-bg-lightness: 15%;
  --message-bg-opacity: 1;
```

Change all the `--metrology-gray-1/2/3` values to `0, 0%, 0%`, and every background will be black.
